{% set name = "atari_py" %}
{% set version = "0.2.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://github.com/openai/atari-py/archive/{{ version }}.zip
    sha256: 0862dd232171c3d073b1e737cd5693d646bf62cc61f82a3b72bec3ecc783b63b
  - url: https://zlib.net/zlib1211.zip  # [win]
    sha256: d7510a8ee1918b7d0cad197a089c0a2cd4d6df05fee22389f67f115e738b178d  # [win]
    folder: atari_py/ale_interface/src/zlib  # [win]

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv  # [not win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
  host:
    - pip
    - python
    - zlib
    - numpy
    - six
  run:
    - python
    - numpy
    - six
    - zlib

test:
  requires:
    - pytest
  imports:
    - atari_py
  commands:
    - pytest --pyargs atari_py.tests

about:
  home: https://github.com/openai/atari-py
  license: GPL-2.0-or-later
  license_family: GPL
  # License file not packaged in pypi, tracked in https://github.com/openai/atari-py/issues/71
  license_file: License.txt
  summary: Python bindings to Atari games
  doc_url: https://pypi.org/project/atari-py/
  dev_url: https://github.com/openai/atari-py

extra:
  recipe-maintainers:
    - mxr-conda
    - oblute
    - rluria14
    - ndmaxar
