{% set name = "atari_py" %}
{% set version = "0.2.6" %}

package: 
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/openai/atari-py/archive/{{ version }}.zip
  sha256: 2ab97bc59f196f91d1b2227ac1cece3ef3fda996d9acf7a8c93e866d4bdc9f3f

build:
  number: 3
  script: {{ PYTHON }} -m pip install . -vv  # [not win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - curl  # [win]
    - m2-unzip  # [win]
  host:
    - pip
    - python
    - zlib
  run:
    - python
    - numpy
    - six
    - zlib

test:
  requires:
    - pytest
  imports:
    - atari_py
  commands:
    - pytest --pyargs atari_py.tests

about:
  home: https://github.com/openai/atari-py
  license: GPL-2.0-or-later
  license_family: GPL
  # License file not packaged in pypi, tracked in https://github.com/openai/atari-py/issues/71
  license_file: License.txt
  summary: "Python bindings to Atari games"
  doc_url: https://pypi.org/project/atari-py/
  dev_url: https://github.com/openai/atari-py

extra:
  recipe-maintainers:
    - oblute
    - rluria14
    - ndmaxar
